# Jekyll Configuration Options
permalink: date
timezone: America/Phoenix
encoding: UTF-8
baseurl: '/PT'
url: "https://felsenst.github.io"
relative_permalinks: false
exclude: [Guardfile, Gemfile, Gemfile.lock]
excerpt_separator: "<!--more-->"
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-archives, :git => 'https://github.com/jekyll/jekyll-archives', :branch => 'master'
  
jekyll-archives:
  enabled:
    - year
  layout: archive
  permalinks:
    year: '/archives/year/:year/'

kramdown:
  header_offset: 1
  syntax_highlighter_opts:
    default_lang: plaintext  
