# Jekyll Configuration Options
permalink: date
timezone: America/Phoenix
encoding: UTF-8
baseurl: 'https://felsenst.github.io/PT'
url: ""
relative_permalinks: false
exclude: [Guardfile, Gemfile, Gemfile.lock]
excerpt_separator: "<!--more-->"
markdown: kramdown
highlighter: rouge

jekyll-archives:
  enabled:
    - year
  layout: archive
  permalinks:
    year: /archives/:year/

kramdown:
  header_offset: 1
  syntax_highlighter_opts:
    default_lang: plaintext  

# Site Configuration Options
contact_email: nobody&#x002b;racartwright&#x0040; &#x0040;nowhere&#x002e;gmail&#x002e;com
owner_link: https://felsenst.github.io/PT/
title: "The Panda's Thumb"
image: /PT/media/roar.jpg
jquery: '3.1.1'
jqueryui: '1.12.1'

# Default options
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      permalink: '/archives/:year/:month/:title.html'
      layout: 'article'
      comments: true
